### ISSUE TITLE
Validation Error: sc:Canvas['height'] does not accept a unicode, only an integer

### ISSUE THREAD

**Issue by RussellMcOrmond** [c7a/cihm-iiif-presentation#1]
I put http://presentation.demo.canadiana.ca/iiif/oocihm.99400/manifest into http://iiif.io/api/presentation/validator/service , and it indicated that there was a validation error.

Apparently "height" and "width" should be integers and not strings (of numbers).

For example,

```
@id: "http://presentation.demo.canadiana.ca/iiif/oocihm.99400/canvas/1",
@type: "sc:Canvas",
label: "Image 1",
height: "3412",
width: "2687",
```

should be:

```
@id: "http://presentation.demo.canadiana.ca/iiif/oocihm.99400/canvas/1",
@type: "sc:Canvas",
label: "Image 1",
height: 3412,
width: 2687,
```

http://iiif.io/api/presentation/2.1/#c-example-manifest-response indicates the same for "@type": "dctypes:Image", with integers used (and without the 'px').

**Comment by SaschaAdler** [comment]
I can't test the manifests with the validator until presentation.demo.canadiana.ca has been updated, but I've used them with both the UV and Mirador demos and we no longer seem to have the "thumbnail issue".

**Comment by RussellMcOrmond** [comment]
I pulled and restarted the Docker image for http://presentation.demo.canadiana.ca/

The above patch fixes the error with sc:Canvas, but not dctypes:Image

Error is:  `Validation Error: dctypes:Image['height'] does not accept a unicode, only an integer`

**Comment by RussellMcOrmond** [comment]
Validator no longer gives errors.  There are some warnings about optional fields which we don't yet set, which we can look into when we are building a production iteration of this.
