### ISSUE TITLE
Convert Canadiana series records to IIIF Collections

### ISSUE THREAD

**Issue by SaschaAdler** [c7a/cihm-iiif-presentation#2]
This is a rather straightforward conversion. Trickier will be converting "portal" and other top-level collections, since we don't currently have a direct reference to a listing of them.

**Comment by RussellMcOrmond** [comment]
As an FYI, I threw http://presentation.demo.canadiana.ca/iiif/collection/oocihm.8_06196 into http://iiif.io/api/presentation/validator/service , and it validated.  Only one warning about optional "description" field not being set.
